# Test workflow Corne Optimot

name: 'Build Corne Optimot'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["QWERTY"]'
      nav: '["invertedT"]'
      layers: '["flip"]'
